### PR TITLE
Squash cockroaches and add Terry

### PR DESCRIPTION
**Pull request by Realswitzer**
please accept i spent too long, also i turned off edits by maintainers so its all or nothing

### CODE REVIEW

**Comment by NightKoneko** [comment]
No conflicts, I think this should merge.

**Comment by ghost** [comment]
LGTM!!! No conflicts and fixes several long-standing issues present in the code. Should be merged ASAP

**Review by ghost — APPROVED** [review]

**Comment by Realswitzer** [comment]
Merge when

**Review by ghost — APPROVED** [review]

**Comment by Realswitzer** [comment]
Thanks for approving the new version.

**Comment by Realswitzer** [comment]
Currently resolving conflicts due to stupid new update.

**Comment by Realswitzer** [comment]
Should be good now, no conflicts.

**Review by ghost — APPROVED** [review]

**Review by NightKoneko — APPROVED** [review]
I approve.

**Review by ghost — APPROVED** [review]
LGTM, compiles and works perfectly for me. Needs to be merged ASAP, no conflicts, and fixes several long-standing issues with the bot.

**Comment by NightKoneko** [comment]
I agree. This **needs** to be merged. It fixes a ludicrous amount of bugs, as well as improving majorly the whole bot overall.

**Review by NightKoneko — CHANGES_REQUESTED** [review]
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Feeduck and Seeduck".

**Review by NightKoneko — APPROVED** [review]
Actually, I will approve it. It makes sense, to be honest.

**Comment by BowDown097** [comment]
Missing the CODE_OF_CONDUCT.md. I can't merge a commit from an author who openly rejects the idea of a welcoming, inclusive, diverse community. Unless if you're willing to address this issue, I will not consider the merge.

**Comment by BowDown097** [comment]
Additionally, the main branch should be renamed from "master" to "main". Remember that the term "master" has been historically oppressive to people of color and perpetuates white supremacy. As a homosexual, transgender, African American female I am rather disappointed in this display of bigotry. Such branch names will not be tolerated under this repository's Code of Conduct.

**Comment by Realswitzer** [comment]
I can rename it to "main" but there is no CODE_OF_CONDUCT.md in the original repository, thus making it impossible to merge.

**Comment by Realswitzer** [comment]
If you could make one for me to merge, I will gladly fix it.

**Comment by Realswitzer** [comment]
Might need to make a new PR. When renaming to main it appears to have broken the PR.

**Pull request closed without merging**
